# Generated by Django 4.2.6 on 2023-10-11 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("image", models.ImageField(upload_to="images/%Y/%m/%d/")),
                ("show_start", models.DateTimeField(auto_now_add=True)),
                (
                    "show_end",
                    models.DateTimeField(default=datetime.datetime(3000, 1, 1, 9, 42)),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
