# Generated by Django 4.2.6 on 2023-10-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0002_calendarconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarconnection",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
    ]
