# Generated by Django 4.2.6 on 2023-10-12 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0003_calendarconnection_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageslide",
            name="show_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
