# Generated by Django 4.2.6 on 2023-10-20 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0004_alter_imageslide_show_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "show_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Ab wann soll dieser Kalender angezeigt werden? (tt.mm.jjjj hh:mm)",
                        verbose_name="Erste Anzeige",
                    ),
                ),
                (
                    "show_end",
                    models.DateTimeField(
                        default=datetime.datetime(3000, 1, 1, 9, 42),
                        help_text="Ab wann soll dieser Banner nicht mehr angezeigt werden? (tt.mm.jjjj hh:mm)",
                        verbose_name="Letzte Anzeige",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="display.calendarconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisplayConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name="imageslide",
            name="image",
            field=models.ImageField(upload_to="images/%Y/%m/%d/", verbose_name="Bild"),
        ),
        migrations.AlterField(
            model_name="imageslide",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="Titel"),
        ),
        migrations.CreateModel(
            name="DisplayImageSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "show_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Ab wann soll dieser Banner angezeigt werden? (tt.mm.jjjj hh:mm)",
                        verbose_name="Erste Anzeige",
                    ),
                ),
                (
                    "show_end",
                    models.DateTimeField(
                        default=datetime.datetime(3000, 1, 1, 9, 42),
                        help_text="Ab wann soll dieser Banner nicht mehr angezeigt werden? (tt.mm.jjjj hh:mm)",
                        verbose_name="Letzte Anzeige",
                    ),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="display.imageslide",
                    ),
                ),
                (
                    "display",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="display.displayconfiguration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="displayconfiguration",
            name="banners",
            field=models.ManyToManyField(
                through="display.DisplayImageSlide", to="display.imageslide"
            ),
        ),
        migrations.AddField(
            model_name="displayconfiguration",
            name="calendars",
            field=models.ManyToManyField(
                through="display.DisplayCalendar", to="display.calendarconnection"
            ),
        ),
        migrations.AddField(
            model_name="displaycalendar",
            name="display",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="display.displayconfiguration",
            ),
        ),
    ]
