# Generated by Django 4.2.6 on 2023-10-20 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0005_displaycalendar_displayconfiguration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayConfigurationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "show_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Ab wann soll dieser Banner angezeigt werden? (tt.mm.jjjj hh:mm)",
                        verbose_name="Erste Anzeige",
                    ),
                ),
                (
                    "show_end",
                    models.DateTimeField(
                        default=datetime.datetime(3000, 1, 1, 9, 42),
                        help_text="Ab wann soll dieser Banner nicht mehr angezeigt werden? (tt.mm.jjjj hh:mm)",
                        verbose_name="Letzte Anzeige",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("gottedienste", "Gottesdienstplan"),
                            ("kalender_countdown", "Countdown aus Kalender"),
                            ("pewview_events", "Ausblick"),
                            ("next_events", "Nächste Ereignisse"),
                        ],
                        max_length=255,
                        verbose_name="Sorte",
                    ),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="display.imageslide",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="display.calendarconnection",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="displayimageslide",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="displayimageslide",
            name="display",
        ),
        migrations.RemoveField(
            model_name="displayconfiguration",
            name="banners",
        ),
        migrations.RemoveField(
            model_name="displayconfiguration",
            name="calendars",
        ),
        migrations.AlterField(
            model_name="displayconfiguration",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name="DisplayCalendar",
        ),
        migrations.DeleteModel(
            name="DisplayImageSlide",
        ),
        migrations.AddField(
            model_name="displayconfigurationitem",
            name="display",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="display.displayconfiguration",
            ),
        ),
    ]
