# Generated by Django 4.2.6 on 2023-10-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0006_displayconfigurationitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayconfigurationitem",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="display.imageslide",
            ),
        ),
        migrations.AlterField(
            model_name="displayconfigurationitem",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="display.calendarconnection",
            ),
        ),
        migrations.AlterField(
            model_name="displayconfigurationitem",
            name="typ",
            field=models.CharField(
                choices=[
                    ("banner", "Banner"),
                    ("gottedienste", "Gottesdienstplan"),
                    ("kalender_countdown", "Countdown aus Kalender"),
                    ("pewview_events", "Ausblick"),
                    ("next_events", "Nächste Ereignisse"),
                ],
                max_length=255,
                verbose_name="Sorte",
            ),
        ),
    ]
