# Generated by Django 4.2.6 on 2023-10-20 01:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0007_alter_displayconfigurationitem_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayconfigurationitem",
            name="typ",
            field=models.CharField(
                choices=[
                    ("banner", "Banner"),
                    ("gottedienste", "Gottesdienstplan"),
                    ("kalender_countdown", "Countdown aus Kalender"),
                    ("preview_events", "Ausblick"),
                    ("next_events", "Nächste Ereignisse"),
                ],
                max_length=255,
                verbose_name="Sorte",
            ),
        ),
    ]
