# Generated by Django 4.2.6 on 2023-10-21 14:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0008_imageslide_show_end_imageslide_show_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayconfigurationitem",
            name="how_long",
            field=models.DurationField(
                default=datetime.timedelta(seconds=7200),
                verbose_name="Wie lange als 'Jetzt' anzeigen?",
            ),
        ),
        migrations.AddField(
            model_name="displayconfigurationitem",
            name="now_start",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Als 'Jetzt' anzeigen"
            ),
        ),
        migrations.AlterField(
            model_name="displayconfigurationitem",
            name="typ",
            field=models.CharField(
                choices=[
                    ("banner", "Banner"),
                    ("gottesdienste", "Gottesdienstplan"),
                    ("kalender_countdown", "Countdown aus Kalender"),
                    ("preview_events", "Ausblick"),
                    ("next_events", "Nächste Ereignisse"),
                ],
                max_length=255,
                verbose_name="Sorte",
            ),
        ),
        migrations.AlterField(
            model_name="imageslide",
            name="show_end",
            field=models.DateTimeField(
                default=datetime.datetime(3000, 1, 1, 9, 42),
                help_text="Ab wann soll dieser Banner nicht mehr angezeigt werden? (tt.mm.jjjj hh:mm)",
                verbose_name="Letzte Anzeige",
            ),
        ),
        migrations.AlterField(
            model_name="imageslide",
            name="show_start",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Ab wann soll dieser Banner angezeigt werden? (tt.mm.jjjj hh:mm)",
                verbose_name="Erste Anzeige",
            ),
        ),
    ]
