# Generated by Django 4.2.6 on 2023-11-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0009_displayconfigurationitem_how_long_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayconfiguration",
            name="show_clock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="displayconfiguration",
            name="two_column",
            field=models.BooleanField(default=True),
        ),
    ]
