# Generated by Django 4.2.6 on 2023-11-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("display", "0010_displayconfiguration_show_clock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayconfiguration",
            name="effect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Kein Effekt"),
                    ("plasma_of_love", "Plasma of Love by Kevin Roast"),
                ],
                default="",
                max_length=1024,
            ),
        ),
    ]
